apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    app: web
spec:
  containers:
    - name: web
      image: arruhu12/tugasdevops-web:v1
      ports:
        - containerPort: 80
      env:
        - name: MYSQL_HOST
          value: mysql-service
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: db_spp
      